actix-web-location: document feature flags
mozilla-services/common-rs pull request #51
Opened 2023-08-06 19:52 UTC by robjtede

2023-08-07 23:17 UTC, jrconlin requested changes
please add CVE to audit, and fix the CI test failure.

2023-08-08 00:23 UTC, robjtede commented
> That's a legit thing to fail on

Really the failure is that features are not strictly additive in this crate, but we've all committed this sin. Anyway, I've told CI to run them separately.

2023-08-08 21:00 UTC, jrconlin commented
Oh, sunsetting Actix3 is very much on my mind. 
The problem is that we have a few customer packages that still need it, so *sigh* might be a bit before we can do something draconian.

2023-08-08 21:01 UTC, jrconlin approved these changes

2023-08-08 21:03 UTC, merged